'use server';
/**
 * @fileOverview This file defines a Genkit flow for editing and copying product descriptions generated by AI.
 *
 * The flow takes an initial product description as input, allows the user to edit it, and then supports copying it to the clipboard.
 *
 * @exports editAndCopyProductDescription - An async function that implements the edit and copy product description flow.
 * @exports EditAndCopyProductDescriptionInput - The input type for the editAndCopyProductDescription function.
 * @exports EditAndCopyProductDescriptionOutput - The return type for the editAndCopyProductDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EditAndCopyProductDescriptionInputSchema = z.object({
  initialDescription: z
    .string()
    .describe('The initial product description generated by AI.'),
});
export type EditAndCopyProductDescriptionInput = z.infer<
  typeof EditAndCopyProductDescriptionInputSchema
>;

const EditAndCopyProductDescriptionOutputSchema = z.object({
  editedDescription: z.string().describe('The edited product description.'),
});
export type EditAndCopyProductDescriptionOutput = z.infer<
  typeof EditAndCopyProductDescriptionOutputSchema
>;

/**
 * An async function that takes an initial product description as input and returns the edited description.
 * @param input - The input object containing the initial product description.
 * @returns A promise that resolves to an object containing the edited product description.
 */
export async function editAndCopyProductDescription(
  input: EditAndCopyProductDescriptionInput
): Promise<EditAndCopyProductDescriptionOutput> {
  return editAndCopyProductDescriptionFlow(input);
}

const editAndCopyProductDescriptionFlow = ai.defineFlow(
  {
    name: 'editAndCopyProductDescriptionFlow',
    inputSchema: EditAndCopyProductDescriptionInputSchema,
    outputSchema: EditAndCopyProductDescriptionOutputSchema,
  },
  async input => {
    // For now, the flow simply returns the initial description as the edited description.
    // In a real application, this flow would likely involve a UI component that allows the user to edit the description.
    return {editedDescription: input.initialDescription};
  }
);
